//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FOLIO
    {
        public int id { get; set; }
        public int room_booked_id { get; set; }
        public int service_id { get; set; }
        public Nullable<int> amount { get; set; }
    
        public virtual ROOM_BOOKED ROOM_BOOKED { get; set; }
        public virtual SERVICE SERVICE { get; set; }
    }
}
