//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GUEST_BOOKING
    {
        public int id { get; set; }
        public int reservation_id { get; set; }
        public string guest_id { get; set; }
        public int room_booked_id { get; set; }
    
        public virtual GUEST GUEST { get; set; }
        public virtual RESERVATION RESERVATION { get; set; }
        public virtual ROOM_BOOKED ROOM_BOOKED { get; set; }
    }
}
