//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelManagement.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class HotelManagementEntities : DbContext
    {
        public HotelManagementEntities()
            : base("name=HotelManagementEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ACCOUNT> ACCOUNTs { get; set; }
        public virtual DbSet<CHARGE> CHARGES { get; set; }
        public virtual DbSet<FOLIO> FOLIOs { get; set; }
        public virtual DbSet<GUEST> GUESTs { get; set; }
        public virtual DbSet<GUEST_BOOKING> GUEST_BOOKING { get; set; }
        public virtual DbSet<INVOICE> INVOICEs { get; set; }
        public virtual DbSet<RESERVATION> RESERVATIONs { get; set; }
        public virtual DbSet<ROOM> ROOMs { get; set; }
        public virtual DbSet<ROOM_BOOKED> ROOM_BOOKED { get; set; }
        public virtual DbSet<ROOMTYPE> ROOMTYPEs { get; set; }
        public virtual DbSet<SERVICE> SERVICEs { get; set; }
    }
}
