//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ROOM
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ROOM()
        {
            this.ROOM_BOOKED = new HashSet<ROOM_BOOKED>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public int roomtype_id { get; set; }
        public string notes { get; set; }
        public Nullable<bool> dirty { get; set; }
        public Nullable<bool> out_of_service { get; set; }
        public Nullable<bool> isActive { get; set; }
    
        public virtual ROOMTYPE ROOMTYPE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ROOM_BOOKED> ROOM_BOOKED { get; set; }
    }
}
